# Marburg Open Educational Resources
#
# This config file is meant for settings that affect the whole course space.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server
# process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Adjust title etc. Depending on serving the site on GitHub or OER, different
# url and baseurl settings have to be used.


##### URL #####################################################################
# Serve on Ilias Uni Marburg OER
# url: "https://ilias.uni-marburg.de"
# baseurl: "/data/UNIMR/lm_data/lm_xxx"

# Serve on GitHub
url: https://geomoer.github.io/
baseurl: "/moer-spotlights"


##### Title ###################################################################
title: Spotlights
name: &name "Lab of Environmental Informatics" # &name is a YAML anchor which can be *referenced later
email: dirk.zeuss@uni-marburg.de
description: >- # this means to ignore newlines until next item
  course course-materials geography remote-sensing marburg-open-educational-resource
  physical-geography environmental-science nature-conservation r SDM

##### Social Sharing ##########################################################
twitter:
  username         : &twitter "EnvIn_UMR"

##### Lecturer settings #######################################################
author:
  name             : "Dirk Zeuss"
  avatar           : "/assets/images/zeuss.jpg"
  bio              : "University of Marburg"
  location         : "Marburg, DE"
  email            : "dirk.zeuss@uni-marburg.de"
  uri              : "https://www.uni-marburg.de/en/fb19/disciplines/physisch/environmentalinformatics"
  home             : "https://www.researchgate.net/profile/Dirk_Zeuss"
  researchgate     : "https://www.researchgate.net/profile/Dirk_Zeuss/stats" # to be included some day
  github           : "GeoMOER"


##### Site configuration ######################################################
title_separator: "|"
excerpt_separator: <!--more-->

search: true

# Build settings
markdown: kramdown
# theme: minima
remote_theme: "GeoMOER/moer-jekyll-theme"
minimal_mistakes_skin    : "contrast" # "default","air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
auto_ids: true

# Default Settings
collections_dir: units

# Includes
include:
  - _pages

# Collections
collections:
  examples:
    output: true
    permalink: /:collection/:title.html
  unit01:
    output: true
    permalink: /:collection/:title.html
  unit02:
    output: true
    permalink: /:collection/:title.html

# Default settings
defaults:
  # examples
  - scope:
      path: ""
      type: examples
    values:
      category: "examples"
      tags: "Examples"
      layout: single
      sidebar:
        nav: "units"
  # unit01
  - scope:
      path: ""
      type: unit01
    values:
      category: "Jekyll & Markdown"
      tags: "Jekyll"
      layout: single
      sidebar:
        nav: "units"

  # pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      sidebar:
        nav: "docs"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-admin
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-algolia

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

github: [metadata]
